# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('last_modified_on', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Compant Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('fax_number', models.CharField(max_length=50, verbose_name='Fax Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('last_modified_on', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('last_modified_on', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('last_modified_on', models.DateField(default=datetime.datetime.now)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('last_modified_on', models.DateField(default=datetime.datetime.now)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Envelope')),
                ('is_from_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Company')),
                ('is_from_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Contact'),
        ),
    ]
