# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20170316_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='desc',
            field=models.CharField(default='--', max_length=1000),
            preserve_default=False,
        ),
    ]
