# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20170318_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='payments_cycle',
            field=models.IntegerField(choices=[(1, b'Monthly'), (2, b'Weekly'), (3, b'Annually')], default=1),
        ),
    ]
